AWSTemplateFormatVersion: "2010-09-09"
Description: "Lambda stack"
Parameters:
  LambdaS3Bucket:
    Type: String
  LambdaS3Key:
    Type: String
  LambdaRoleArn:
    Type: String
Resources:
  HelloLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: hello-lambda
      Handler: hello.lambda_handler
      Role: !Ref LambdaRoleArn
      Runtime: python3.11
      Code:
        S3Bucket: !Ref LambdaS3Bucket
        S3Key: !Ref HelloLambdaS3Key
      Timeout: 3
  GoodbyeLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: goodbye-lambda
      Handler: goodbye.lambda_handler
      Role: !Ref LambdaRoleArn
      Runtime: python3.11
      Code:
        S3Bucket: !Ref LambdaS3Bucket
        S3Key:  !Ref GoodbyeLambdaS3Key
      Timeout: 3