AWSTemplateFormatVersion: "2010-09-09"
Description: "Root stack"
Resources:
  S3Stack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://swiftiecx-project01.s3.ap-northeast-1.amazonaws.com/templates/s3.yaml

  IAMStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://swiftiecx-project01.s3.ap-northeast-1.amazonaws.com/templates/iam.yaml

  LambdaStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://swiftiecx-project01.s3.ap-northeast-1.amazonaws.com/templates/lambda.yaml
      Parameters:
        LambdaS3Bucket: swiftiecx-project01
        HelloLambdaS3Key: lambda/hello.zip
        GoodbyeLambdaS3Key: lambda/goodbye.zip
        EchoLambdaS3Key: lambda/echo.zip
        TimeLambdaS3Key: lambda/time.zip
        LambdaRoleArn: !GetAtt IAMStack.Outputs.LambdaExecutionRoleArn

