name: Deploy CloudFormation

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-1

    - name: Upload templates
      run: aws s3 cp templates/ s3://swiftiecx-project01/templates/ --recursive

    - name: Upload Lambda code (如果有zip包)
      run: aws s3 cp lambda/ s3://swiftiecx-project01/lambda/ --recursive

    - name: Deploy CloudFormation stack
      run: |
        aws cloudformation deploy \
          --template-file templates/root.yaml \
          --stack-name project-root-stack \
          --capabilities CAPABILITY_NAMED_IAM
